- name: restart postfix
  service:
    name: postfix
    enabled: true
    state: restarted

- name: postmap sasl_passwd
  command:
    cmd: postmap "{{ sasl_passwd_dest }}"
  notify:
    - secure sasl_passwd

- name: secure sasl_passwd
  file:
    path: "{{ item }}"
    owner: "{{ sasl_passwd_owner }}"
    group: "{{ sasl_passwd_group }}"
    mode: "{{ sasl_passwd_mode }}"
  loop:
    - "{{ sasl_passwd_dest }}"
    - "{{ sasl_passwd_dest }}.db"

- name: newaliases
  command:
    cmd: newaliases
