docker_dependencies:
  - ca-certificates
  - curl

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_gpg_key_url: "https://download.docker.com/linux/debian/gpg"
docker_gpg_keyring: "/etc/apt/keyrings/docker.asc"
docker_repo_url: "https://download.docker.com/linux/debian"
