ufw_installed: true

sasl_passwd_src: sasl_passwd.j2
sasl_passwd_dest: /etc/postfix/sasl/sasl_passwd
sasl_passwd_owner: root
sasl_passwd_group: root
sasl_passwd_mode: "0600"

main_cf_src: main.cf.j2
main_cf_dest: /etc/postfix/main.cf

smtp_server: smtp.gmail.com
smtp_port: 587
sasl_mail:
sasl_pass:

aliases:
  - "root: {{ sasl_mail }}"
