- name: apt install postfix
  apt:
    name:
      - postfix
    state: latest

- name: sasl_passwd config
  template:
    src: "{{ sasl_passwd_src }}"
    dest: "{{ sasl_passwd_dest }}"
    owner: "{{ sasl_passwd_owner }}"
    group: "{{ sasl_passwd_group }}"
    mode: "{{ sasl_passwd_mode }}"
  notify:
    - postmap sasl_passwd

- name: postfix config
  template:
    src: "{{ main_cf_src }}"
    dest: "{{ main_cf_dest }}"
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart postfix

- name: add email aliases
  lineinfile:
    path: /etc/aliases
    line: "{{ item }}"
  loop: "{{ aliases }}"
  notify:
    - newaliases

- name: ufw allow postfix
  ufw:
    rule: allow
    name: postfix
  when: ufw_installed
