- name: update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: upgrade apt packages
  ansible.builtin.apt:
    upgrade: true

- name: install apt packages
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    state: latest

- name: prohibit direct root login
  ansible.builtin.user:
    name: root
    shell: /usr/sbin/nologin
