- name: install ufw package
  ansible.builtin.apt:
    name:
      - ufw
    state: latest

- name: disable ipv6 in ufw
  ansible.builtin.lineinfile:
    path: "{{ ufw_config }}"
    regexp: "^IPV6="
    line: "IPV6=no"
  when: ufw_disable_ipv6

- name: set ufw default incoming to "{{ ufw_default_incoming }}"
  community.general.ufw:
    default: "{{ ufw_default_incoming }}"
    direction: incoming

- name: set ufw default outgoing to "{{ ufw_default_outgoing }}"
  community.general.ufw:
    default: "{{ ufw_default_outgoing }}"
    direction: outgoing

- name: set ufw rules
  community.general.ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
  loop: "{{ ufw_rules }}"

- name: enable ufw
  community.general.ufw:
    state: enabled
