- name: apt install ufw
  apt:
    name:
      - ufw
    state: latest

- name: ufw config
  copy:
    src: "{{ ufw_config_src }}"
    dest: "{{ ufw_config_dest }}"
    owner: root
    group: root
    mode: "0644"

- name: ufw default allow outgoing
  ufw:
    default: "{{ ufw_default_incoming }}"
    direction: incoming

- name: ufw default allow outgoing
  ufw:
    default: "{{ ufw_default_outgoing }}"
    direction: outgoing

- name: ufw rules
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
  loop: "{{ ufw_rules }}"

- name: ufw enable
  ufw:
    state: enabled
  notify:
    - restart ufw
