- name: apt update cache
  apt:
    update_cache: true

- name: apt upgrade packages
  apt:
    upgrade: true

- name: apt install sysadmin packages
  apt:
    name:
      - neovim
      - btop
      - qemu-guest-agent
    state: latest
